In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 150)

In [2]:
clean_jobs = pd.read_csv("../data/raw/clean_jobs.csv")
gsearch_jobs = pd.read_csv("../data/raw/gsearch_jobs.csv")

In [3]:
print("Clean Jobs Dataset Shape:", clean_jobs.shape)
print("Google Search Jobs Dataset Shape:", gsearch_jobs.shape)

Clean Jobs Dataset Shape: (1048, 10)
Google Search Jobs Dataset Shape: (61953, 27)

In [4]:
clean_jobs.head()

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
0,1,Data Analyst,Meta,"New York, NY",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
1,2,Data Analyst,Meta,"San Francisco, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
2,3,Data Analyst,Meta,"Los Angeles, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
3,4,Data Analyst,Meta,"Washington, DC",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
4,5,Data Analyst II,Pinterest,"Chicago, IL",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-16,NaN,NaN,About Pinterest\n\nMillions of people around t...

In [5]:
gsearch_jobs.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,15 hours ago,Full-time,True,101K–143K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,12 hours ago,Full-time,NaN,NaN,data analyst,2023-08-04 03:00:13.797776,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,18 hours ago,Full-time,NaN,NaN,data analyst,2023-08-04 03:00:13.797776,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,12 hours ago,Contractor,True,15–25 an hour,data analyst,2023-08-04 03:00:13.797776,United States,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,7 hours ago,Contractor,NaN,90K–110K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [6]:
print("Google Search Columns")
print(gsearch_jobs.columns.tolist())

Google Search Columns
['Unnamed: 0', 'index', 'title', 'company_name', 'location', 'via', 'description', 'extensions', 'job_id', 'thumbnail', 'posted_at', 'schedule_type', 'work_from_home', 'salary', 'search_term', 'date_time', 'search_location', 'commute_time', 'salary_pay', 'salary_rate', 'salary_avg', 'salary_min', 'salary_max', 'salary_hourly', 'salary_yearly', 'salary_standardized', 'description_tokens']

In [7]:
print("Clean Jobs Columns")
print(clean_jobs.columns.tolist())

Clean Jobs Columns
['id', 'title', 'company', 'location', 'link', 'source', 'date_posted', 'work_type', 'employment_type', 'description']

In [8]:
clean_jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1048 non-null   int64
 1   title            1048 non-null   str
 2   company          1046 non-null   str
 3   location         1033 non-null   str
 4   link             1048 non-null   str
 5   source           959 non-null    str
 6   date_posted      1025 non-null   str
 7   work_type        0 non-null      float64
 8   employment_type  0 non-null      float64
 9   description      1044 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 4.5 MB

In [9]:
gsearch_jobs.info()

<class 'pandas.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  str
 3   company_name         61953 non-null  str
 4   location             61916 non-null  str
 5   via                  61944 non-null  str
 6   description          61953 non-null  str
 7   extensions           61953 non-null  str
 8   job_id               61953 non-null  str
 9   thumbnail            38194 non-null  str
 10  posted_at            61763 non-null  str
 11  schedule_type        61707 non-null  str
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  str
 14  search_term          61953 non-null  str
 15  date_time            61953 non-null  str
 16  search_location      61953 non-null  str
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  str
 19  salary_rate          10088 non-null  str
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  str
dtypes: float64(7), int64(2), object(1), str(17)
memory usage: 286.5+ MB

In [10]:
clean_jobs.isnull().sum().sort_values(ascending=False)

work_type          1048
employment_type    1048
source               89
date_posted          23
location             15
description           4
company               2
id                    0
title                 0
link                  0
dtype: int64

In [11]:
gsearch_jobs.isnull().sum().sort_values(ascending=False)

commute_time           61953
salary_yearly          57884
salary_hourly          56053
salary_max             52441
salary_min             52441
salary                 51865
salary_pay             51865
salary_rate            51865
salary_standardized    51865
salary_avg             51865
work_from_home         33973
thumbnail              23759
schedule_type            246
posted_at                190
location                  37
via                        9
index                      0
title                      0
Unnamed: 0                 0
extensions                 0
job_id                     0
company_name               0
description                0
date_time                  0
search_location            0
search_term                0
description_tokens         0
dtype: int64

In [12]:
print("Clean Jobs:", clean_jobs.duplicated().sum())

Clean Jobs: 0

In [13]:
print("Google Search:", gsearch_jobs.duplicated().sum())

Google Search: 0

In [14]:
clean_jobs.describe(include="all")

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
count,1048.000000,1048,1046,1033,1048,959,1025,0.0,0.0,1044
unique,NaN,523,632,358,1048,3,36,NaN,NaN,933
top,NaN,Data Analyst,Meta,United States,https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-06-06,NaN,NaN,"As a Data Engineer at Meta, you will shape the..."
freq,NaN,152,70,73,1,862,108,NaN,NaN,11
mean,1314.083969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,772.822422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,616.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1303.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2033.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2534.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
gsearch_jobs.describe(include="all")

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
count,61953.000000,61953.000000,61953,61953,61916,61944,61953,61953,61953,38194,61763,61707,27980,10088,61953,61953,61953,0.0,10088,10088,10088.000000,9512.000000,9512.000000,5900.000000,4069.000000,10088.000000,61953
unique,NaN,NaN,23292,13429,1254,1024,42976,9668,58775,14686,109,32,1,2225,1,6588,1,NaN,2225,3,NaN,NaN,NaN,NaN,NaN,NaN,11276
top,NaN,NaN,Data Analyst,Upwork,Anywhere,via LinkedIn,"The Sr. Data Analyst, Marketing Operations wil...","['17 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJjb21wYW...,https://encrypted-tbn0.gstatic.com/images?q=tb...,18 hours ago,Full-time,True,77K–116K a year,data analyst,2023-08-04 03:00:13.797776,United States,NaN,77K–116K,an hour,NaN,NaN,NaN,NaN,NaN,NaN,[]
freq,NaN,NaN,6444,7533,18067,20475,258,841,75,3505,4132,45082,27980,413,61953,10,61953,NaN,413,5900,NaN,NaN,NaN,NaN,NaN,NaN,13352
mean,30976.000000,1139.077333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42100.231239,34846.281874,50487.856787,40.539588,104115.406718,92289.425683,NaN
std,17884.434951,690.256113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55893.993519,45843.034891,67366.522273,22.214540,36024.388492,43277.933820,NaN
min,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.250000,8.000000,10.000000,7.250000,29289.840000,15080.000000,NaN
25%,15488.000000,553.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.500000,19.520000,45.000000,23.265000,80000.180000,62400.000000,NaN
50%,30976.000000,1111.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,50.000000,75.000000,33.500000,96500.000000,88400.000000,NaN
75%,46464.000000,1685.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92500.000000,77000.000000,110000.000000,55.000000,120000.000000,117500.000000,NaN
max,61952.000000,3228.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550000.000000,450000.000000,850000.000000,300.000000,550000.000000,624000.000000,NaN

In [16]:
clean_jobs.sample(5)

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
961,2367,"Sr. Analyst, Retail Global Analytics and Insig...",Universal Products & Experiences,"Universal City, CA",https://www.linkedin.com/jobs/view/4230884297,linkedin,NaN,NaN,NaN,**Company Description**\n NBCUniversal is one ...
490,1258,Sr. Data Scientist (Commercial Analytics),Cedar,United States,https://www.linkedin.com/jobs/view/sr-data-sci...,LinkedIn,2025-05-21,NaN,NaN,Our healthcare system is the leading cause of ...
346,863,"Sr. Analyst, Data & Analytics",Authentic Brands Group,"New York, NY",https://www.linkedin.com/jobs/view/sr-analyst-...,LinkedIn,2025-05-16,NaN,NaN,Who We Are\n\n\n\n\nAuthentic is a unified pla...
563,1473,Data Engineer,Middle Seat,"Washington, DC",https://www.linkedin.com/jobs/view/data-engine...,LinkedIn,2025-05-19,NaN,NaN,Middle Seat is a full-service media and fundra...
638,1649,**** ********* (******* *********),*****,"*********, *********, *****",https://in.linkedin.com/jobs/view/data-scienti...,LinkedIn,2025-06-04,NaN,NaN,About the company:\n\n\n\n\nAbout Titan\n\nAt ...

In [17]:
gsearch_jobs.sample(5)

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,posted_at,schedule_type,work_from_home,salary,search_term,date_time,search_location,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
28186,28186,1159,Data Analytics Expert - First Party Fraud Prev...,USAA,"Colorado Springs, CO",BeBee,Why Choose USAA\n\nUSAA offers a unique opport...,"['17 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5dGljcyBFeHBlcn...,https://serpapi.com/searches/679c4ad4937cf399c...,17 hours ago,Full-time,NaN,NaN,data analyst,2025-01-31 04:00:20.864387,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['sas', 'sql']"
52921,52921,171,Data Reporting Analyst,Confidential,Anywhere,via LinkedIn,Top 3 Required Skills:\n\n1. Utilize SSRS & SQ...,"['6 hours ago', 'Work from home', 'Contractor'...",eyJqb2JfdGl0bGUiOiJEYXRhIFJlcG9ydGluZyBBbmFseX...,https://encrypted-tbn0.gstatic.com/images?q=tb...,6 hours ago,Contractor,True,NaN,data analyst,2023-01-26 04:00:32.280633,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['ssis', 'ssrs', 'power_bi', 'sql']"
28296,28296,1269,Data Analyst,Morgan Community College,"Fort Morgan, CO",BeBee,Job Title\n\nData Analyst Position\n\nPosition...,"['20 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJjb21wYW...,https://serpapi.com/searches/678b27485f508e7e3...,20 hours ago,Full-time,NaN,NaN,data analyst,2025-01-18 04:00:09.229249,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['excel']
27119,27119,92,Weekend Data Analyst for US Market Insights,Yoh,United States,BeBee,"Join Yoh, a Day & Zimmermann company, as a Wee...","['24 hours ago', 'Full-time', 'No degree menti...",eyJqb2JfdGl0bGUiOiJXZWVrZW5kIERhdGEgQW5hbHlzdC...,https://serpapi.com/searches/6778b24e38479bf4e...,24 hours ago,Full-time,NaN,NaN,data analyst,2025-01-04 04:00:15.893572,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
54645,54645,1895,Data Science Lead,Invenia Group,Anywhere,via LinkedIn,Are you looking for a change? Do you want to w...,"['11 hours ago', 'Work from home', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIFNjaWVuY2UgTGVhZCIsIm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,11 hours ago,Full-time,True,NaN,data analyst,2023-03-14 03:00:50.375375,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['pandas', 'python', 'numpy']"